### ISSUE TITLE
Cancelar/remover produtos e pedidos

### ISSUE THREAD

**Issue by Lirca** [samasti/noosfero#40]
https://cirandas.net/myprofile/uilikande/plugin/consumers_coop/cycle/edit/439
removo o kg de abobrinha do pedido da Karina, mas nao acontece nada! nao remove. Tentei modificar a quantidade que quero remover, colocar que vou remover 1kg, mas nao responde

nesse mesmo link, nao consigo remover/cancelar os pedidos que eu fiz de teste

**Comment by brauliobo** [comment]
@Lirca arrumando o total

**Comment by brauliobo** [comment]
@Lirca está no cirandas a correção, pode testar?
