### ISSUE TITLE
Nome produtos duplicado e oculto

### ISSUE THREAD

**Issue by Lirca** [samasti/noosfero#41]
https://cirandas.net/myprofile/uilikande/plugin/consumers_coop/product
Estou tentando ativar o produto "repolho roxo", mas nao consigo. Também nao consigo eliminar o _ do nome do produto "repolho roxo_" porque quando elimino o _ fala que esse nome já está sendo usado (mas quando busco "roxo", só aparece esse repolho roxo da Dona Cida).
Como ativar o produto?

**Comment by hugomelo** [comment]
Oi Lirca, me desculpe, só vi agora esse problema.
Eu tentei mudar o nome agora e funcionou. Talvez não esteja claro nessa tela de produtos, mas apenas aparecem os produtos ativos. Pra ver os inativos, você precisa mudar o filtro ali naquela barra de filtros em **situação**. Eu também consegui ativá-lo, parece que foi algum problema já resolvido. Eu o desativei de novo pra não dar nenhum problema nos pedidos aí. Se quiser, reative-o lá.
valeu!
