### ISSUE TITLE
Produtos não são carregados ao abrir uma nova feira

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#46]
Estou tentando abrir uma nova feira, Ciclo n.179 da Rede Agroecológica Caiçara[1]. Preencho todos os itens e a feira é criada. Logo abaixo do botão "Salvar", a mensagem é de que os produtos estão sendo carregados na feira porém essa operação nunca termina. Se eu clico no botão "Salvar e Abrir Pedidos", a feira é aberta porém sem nenhum produto disponível.

Estou usando Chrome Version 56.0.2924.28 beta (64-bit), mas também tentei no Firefox e no Android com os mesmos resultados.

Isso impossibilita a criação da feira dessa semana.

[1] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1668

**Comment by hugomelo** [comment]
Resolvido!
