### ISSUE TITLE
Pedidos aparecem dobrados para o fornecedor na fase de compras

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#57]
Na lista que aparecem as compras por fornecedor o número de pedidos está dobrado. Por exemplo, para o fornecedor Diogo há um pedido de 2 pães com valor total de 14 reais na lista de compras[1], porém na lista de pedidos[2] só há um pedido (Silvia Moreira Rojo Vega) com 1 pão. Não confirmei se isso acontece com todos os produtos de cada fornecedor mas já vi esse bug aparecer em mais de um ciclo.

[1] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1748?view=purchases

[2] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1748?view=orders

**Comment by hugomelo** [comment]
Adicionamos uma aba na planilha de fornecedores que mostra a quantidade de pedidos vs compras. Está realmente mostrando que tem muito erro, mas já dá pra saber onde está errado.
Ainda vamos trabalhar pra resolver essas falhas

**Comment by hugomelo** [comment]
Resolvido. Por favor, acompanhe essa segunda aba e verifique se está tudo, ok. Caso, algum pedido esteja incorreto, por favor, reabra esse ticket.
