### ISSUE TITLE
Pedidos inexistentes aparecem na fase de compras

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#58]
Na lista de compras por fornecedor[1] há dois pedidos para duas fornecedoras, Panacéia (Repelente) e Keila Kumakura (Desodorante natural) que não constam dos pedidos de nenhum dos consumidores na lista de pedidos[2]. As fornecedoras receberam um email do Cirandas avisando dos pedidos porém ficaram confusas que estes não constam da listagem de pedidos por consumidor.

[1] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1748?view=purchases

[2] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1748?view=orders

**Comment by brauliobo** [comment]
@diogomatsubara acredita que alguém pode ter adicionado o produto e depois removido ou que algum pedido que continha esses produtos foram cancelados? temos problemas quando produtos devem ser removidos

**Comment by brauliobo** [comment]
aparentemente @hugomelo resolveu, pode tentar reproduzir novamente?

**Comment by hugomelo** [comment]
resolvido. O problema era ao remover.
@diogomatsubara, por favor, reabra esse ticket se isso acontecer de novo.
valeu!
