### ISSUE TITLE
Inconsistência nos relatórios de pedidos e produtos. Produtos com o mesmo código com nomes diferentes.

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#59]
Há uma inconsistência nos nomes de um produto de um mesmo fornecedor nos relatórios por produtos e por fornecedores.

No ciclo 183, exporte as planilhas geradas pelo cirandas na fase de pedidos[1] selecionando todos os pedidos.

Note como no relatório de pedidos há um item da fornecedora Néia no pedido de Angela (código do pedido: 3): Código do produto: 246894 Fornecedora: Néia Nome do produto: HT - Azedinha com abutilon. No relatório de produtos os mesmo produto (mesmo id: 246894) aparece com o nome HT - Azedinha + Capuchinha. Na listagem dos produtos dessa fornecedora[2] já foi arrumado o item com o nome correto (Azedinha com abutilon) porém na listagem gerada na planilha ele ainda vem com o nome incorreto.

[1] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/edit/1748?view=orders
[2] http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/product

**Comment by hugomelo** [comment]
Oi Diogo,
Isso acontece porque alguém editou o nome do produto na tela de [edição de produtos]( http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/product) em vez de criar um novo produto e desabilitar o antigo.

O nome fica diferente quando editado porque, em geral, o consumidor pode querer manter um nome diferente do apresentado pelo fornecedor (por isso, temos duas camadas de produto, o *base* do fornecedor e o *distribuído* do grupo) , mas as pessoas confundem essa funcionalidade quando querem modificar um produto oferecido em vez de criar um novo. Quando fazem isso, além do histórico perdido, elas divergem o nome do produto do grupo do nome do produto do fornecedor. 

Como uma forma de evitar que isso aconteça a gente vai colocar o nome do produto no fornecedor como uma label abaixo do input do produto sempre que for alterado.

Pra resolver seu problema agora, pega o nome que está aparecendo pro fornecedor e arruma na edição do produto, desabilita e cria um novo produto com o nome que você quer q apareça agora.
Se tiver mais alguma dúvida sobre isso pode perguntar aqui mesmo

**Comment by brauliobo** [comment]
fechando, por enquanto o nome ainda fica como o nome do produto do fornecedor. talvez no futuro colocar também o nome do coletivo

**Comment by diogomatsubara** [comment]
Mais um membro do coletivo teve esse mesmo problema. Acho confuso, e pelo visto nossos usuários também acham, essa separação entre produtos base (fornecedor) e distribuido (grupo) pois a UI não diferencia em nada eles. Se os produtos tem o mesmo ID então eles deveriam ser o mesmo objeto, imagino eu e não importa onde é feita a alteração os nomes serem alterados em todos os lugares. O caso de uso que você explica não ficou claro e deixas as coisas ainda mais confusas. Mas tudo bem, obrigado pelo workaround de qualquer forma.

**Comment by brauliobo** [comment]
oi @diogomatsubara, infelizmente a separação é necessário pela natureza de rede do sistema: um fornecedor pode, em tese, ser usado por mais de um coletivo.

sugira por favor pra gente maneiras de deixar essa separação clara na interface
