### ISSUE TITLE
Usuários moderadores tem acesso negado ao editar produtos

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#62]
Alguns usuários com a permissão de moderadores (Agatha de Morais Lopes e Juan Blanco) informaram que não conseguem acessar a página de edição do seus [produtos](http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/product)

O workaround no momento foi dar permissão de administrador para esses usuários.

**Comment by hugomelo** [comment]
Oi Diogo,
Realmente, apenas administradores conseguem editar produtos. Moderadores apenas trabalham com conteúdo e pessoas.

**Comment by diogomatsubara** [comment]
Não seria interessante que os fornecedores pudessem gerenciar seus próprios produtos? E a permissão para tal não seria adequada como moderador? A razão de reportar esse bug também é com o intuito de talvez incluir essa melhoria no futuro
