### ISSUE TITLE
Não é possível abrir um novo ciclo. Erro ao carregar os controles para escolher as datas

### ISSUE THREAD

**Issue by diogomatsubara** [samasti/noosfero#64]
Ao tentar criar uma nova feira em http://cirandas.net/myprofile/rede-agroecologica-caicara/plugin/consumers_coop/cycle/new os controles para escolher a data não são carregados.

Os erros que aparecem no console javascript são:
Uncaught TypeError: Cannot read property 'format' of undefined
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by hugomelo** [comment]
Resolvido!
