### ISSUE TITLE
Não é possível mais tornar um produto indisponível

### ISSUE THREAD

**Issue by dtygel** [samasti/noosfero#70]
Produto indisponível era uma opção na edição do produto. Não existe mais. É bug ou opção real?

**Comment by hugomelo** [comment]
Parece que ainda é uma opção. Se você clicar em **editar informações básicas** vai aparecer um radio pra definir se está disponível **sim** ou **não**.
Tenta lá por favor e reabre se tiver outro problema e eu não tiver entendido.
